-- Migration for Engine 4.2

-- 1. Updates to 'runs' table
ALTER TABLE runs ADD COLUMN IF NOT EXISTS score_version TEXT DEFAULT '4.1';
ALTER TABLE runs ADD COLUMN IF NOT EXISTS quality TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS trend JSONB;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS comparison JSONB;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS achievements TEXT[];

-- 2. Updates to 'athletes' table
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS engine_version TEXT;
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS last_run_date TIMESTAMP WITH TIME ZONE;

-- 3. New Table: score_replay
CREATE TABLE IF NOT EXISTS score_replay (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    run_id BIGINT REFERENCES runs(id),
    athlete_id BIGINT REFERENCES athletes(id),
    score_version TEXT,
    score FLOAT,
    decoupling FLOAT, 
    wcf FLOAT,
    percentile FLOAT,
    tref_sec FLOAT,
    details JSONB
);

-- 4. New Table: achievements_log
CREATE TABLE IF NOT EXISTS achievements_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    athlete_id BIGINT REFERENCES athletes(id),
    run_id BIGINT REFERENCES runs(id),
    achievement_name TEXT,
    icon TEXT
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_replay_run_id ON score_replay(run_id);
CREATE INDEX IF NOT EXISTS idx_runs_athlete_date ON runs(athlete_id, date DESC);
